add_custom_command( TARGET AgrioClang POST_BUILD COMMAND mkdir -p ${CMAKE_BINARY_DIR}/bin )
macro( agrio_clang_install file )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/agrio_llvm/bin)
   add_custom_command( TARGET AgrioClang POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( agrio_clang_install )

macro( agrio_clang_install_and_symlink file symlink )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/agrio_llvm/bin)
   add_custom_command( TARGET AgrioClang POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   add_custom_command( TARGET AgrioClang POST_BUILD COMMAND cd ${CMAKE_BINARY_DIR}/bin && ln -sf ${file} ${symlink} )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( agrio_clang_install_and_symlink )

macro( agrio_tool_install file )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/tools/bin)
   add_custom_command( TARGET AgrioTools POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( agrio_tool_install )

macro( agrio_tool_install_and_symlink file symlink )
   set(BINARY_DIR ${CMAKE_BINARY_DIR}/tools/bin)
   add_custom_command( TARGET AgrioTools POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/${file} ${CMAKE_BINARY_DIR}/bin/ )
   add_custom_command( TARGET AgrioTools POST_BUILD COMMAND cd ${CMAKE_BINARY_DIR}/bin && ln -sf ${file} ${symlink} )
   install(FILES ${BINARY_DIR}/${file}
      DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
      PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endmacro( agrio_tool_install_and_symlink )

macro( agrio_libraries_install)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/lib)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/include)
   install(DIRECTORY ${CMAKE_BINARY_DIR}/lib/ DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
   install(DIRECTORY ${CMAKE_BINARY_DIR}/include/ DESTINATION ${CMAKE_INSTALL_FULL_INCLUDEDIR})
endmacro( agrio_libraries_install )

agrio_clang_install_and_symlink(llvm-ranlib agrio-ranlib)
agrio_clang_install_and_symlink(llvm-ar agrio-ar)
agrio_clang_install_and_symlink(llvm-nm agrio-nm)
agrio_clang_install_and_symlink(llvm-objcopy agrio-objcopy)
agrio_clang_install_and_symlink(llvm-objdump agrio-objdump)
agrio_clang_install_and_symlink(llvm-readobj agrio-readobj)
agrio_clang_install_and_symlink(llvm-readelf agrio-readelf)
agrio_clang_install_and_symlink(llvm-strip agrio-strip)
agrio_clang_install(opt)
agrio_clang_install(llc)
agrio_clang_install(lld)
agrio_clang_install(ld.lld)
agrio_clang_install(ld64.lld)
agrio_clang_install(clang-7)
agrio_clang_install(wasm-ld)
agrio_tool_install(agrio-pp)
agrio_tool_install(agrio-wast2wasm)
agrio_tool_install(agrio-wasm2wast)
agrio_tool_install(agrio-cc)
agrio_tool_install(agrio-cpp)
agrio_tool_install(agrio-ld)
agrio_tool_install(agrio-abigen)
agrio_tool_install(agrio-abidiff)
agrio_tool_install(agrio-init)
agrio_clang_install(../lib/LLVMAgrioApply${CMAKE_SHARED_LIBRARY_SUFFIX})
agrio_clang_install(../lib/LLVMAgrioSoftfloat${CMAKE_SHARED_LIBRARY_SUFFIX})
agrio_clang_install(../lib/agrio_plugin${CMAKE_SHARED_LIBRARY_SUFFIX})
agrio_libraries_install()
